bumoProxy:
  restart: always
  image: jwilder/nginx-proxy
  volumes:
  - /var/run/docker.sock:/tmp/docker.sock:ro
  ports:
  - 80:80
  - 443:443

bumoReactData:
  image: daocloud.io/akinoniku/bumo_react:master-e0cd63d

bumoNginx:
  image: nginx:1.10
  restart: always
  volumes:
  - ./nginx.conf:/etc/nginx/nginx.conf:ro
  expose:
  - 80
  - 443
  volumes_from:
  - bumoReactData:ro
  environment:
  - VIRTUAL_HOST=*.3acg.com
